import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
	return (
		<>
			<Head>
				<title>Next Basic</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="" />
			</Head>
			<main>
				<nav className="flex justify-between items-center w-100 shadow p-3 gap-4 link-area">
					<Link href="/">Home</Link>
					<>
						<Link href="hooks">Hooks</Link>
					</>
				</nav>
			</main>
		</>
	);
}
